name: Create Qase Test Run

on:
  workflow_dispatch:

jobs:
  create-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Qase Test Run
        uses: qase-tms/qase-cloud-actions/create-run@v1
        with:
          token: ${{ secrets.QASE_API_TOKEN }}
          projectCode: "HRC"   
          title: "GitHub Actions Run"
          includeAll: true
